# Generated by Django 4.2.1 on 2023-08-14 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_paycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayContact',
        ),
    ]
