# Generated by Django 4.2.1 on 2023-08-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_usermodel_email'),
        ('accounts', '0005_delete_paycontact'),
    ]

    operations = [
    ]
