# Generated by Django 4.2.1 on 2023-08-02 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_wallethistory_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='wallet_history_entries',
            field=models.ManyToManyField(to='transactions.wallethistory'),
        ),
    ]
