# Generated by Django 4.2.1 on 2023-08-02 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_wallet_wallet_history_entries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='wallet_history_entries',
        ),
    ]
