# Generated by Django 4.2.1 on 2023-08-03 08:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_remove_wallet_wallet_history_entries'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='transactions.wallet'),
        ),
    ]
