# Generated by Django 4.2.1 on 2023-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0005_wallethistory_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='wallet_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
