# Generated by Django 4.2.1 on 2023-08-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0008_alter_wallethistory_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallethistory',
            name='description',
            field=models.CharField(choices=[('redeemed', 'Redeemed'), ('credited', 'Credited')], default='null', max_length=100),
        ),
    ]
