# Generated by Django 4.2.1 on 2023-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0009_alter_wallethistory_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='transaction_id',
            field=models.IntegerField(null=True),
        ),
    ]
