# Generated by Django 4.2.1 on 2023-08-07 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_pickuprequest_confirm_otp'),
        ('transactions', '0010_wallethistory_transaction_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallethistory',
            name='order_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.orders'),
        ),
    ]
