# Generated by Django 4.2.1 on 2023-08-14 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0013_paycontact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PayContact',
        ),
    ]
