# Generated by Django 4.2.1 on 2023-08-14 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0015_paycontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paycontact',
            name='type',
            field=models.TextField(default='customer'),
        ),
    ]
