# Generated by Django 4.2.1 on 2023-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuprequest',
            name='confirmOtp',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
