# Generated by Django 4.2.1 on 2023-07-10 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_pickuprequest_confirmotp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pickuprequest',
            old_name='confirmOtp',
            new_name='confirm_otp',
        ),
    ]
