# Generated by Django 4.2.1 on 2023-07-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_orderitems_item_id_alter_orderitems_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('on hold', 'On Hold'), ('rejected', 'Rejected')], default='live', max_length=100),
        ),
    ]
