# Generated by Django 4.2.1 on 2023-07-11 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orders_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('live', 'Live'), ('on hold', 'On Hold'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='live', max_length=100),
        ),
    ]
