# Generated by Django 4.2.1 on 2023-07-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_rename_status_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('live', 'Live'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='live', max_length=100),
        ),
    ]
