# Generated by Django 4.2.1 on 2023-07-20 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_alter_orders_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_status',
            field=models.CharField(choices=[('live', 'Live'), ('onhold', 'On Hold'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('picked', 'Picked'), ('paid', 'Paid')], default='onhold', max_length=100),
        ),
        migrations.AlterField(
            model_name='pickuprequest',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('completed', 'Completed')], default='requested', max_length=100),
        ),
    ]
