# Generated by Django 4.2.1 on 2023-07-24 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_usertransactiondetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertransactiondetails',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
