# Generated by Django 4.2.1 on 2023-08-24 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_pickuprequest_confirm_otp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemrate',
            name='rate',
            field=models.TextField(max_length=10),
        ),
    ]
