# Generated by Django 4.2 on 2023-09-30 11:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0015_alter_itemrate_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyCartItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8)),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.itemrate')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'item_id')},
            },
        ),
    ]
