# Generated by Django 4.2 on 2023-10-31 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_mycartitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuprequest',
            name='landmark',
            field=models.TextField(blank=True, null=True),
        ),
    ]
